version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  loadbalancer:
    build:
      context: ./load_balancer
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer1:
    build:
      context: ./consumer
    environment:
      - CONSUMER_ID=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer2:
    build:
      context: ./consumer
    environment:
      - CONSUMER_ID=2
    depends_on:
      rabbitmq:
        condition: service_healthy

  provider1:
    build:
      context: ./producer
    environment:
      - PROVIDER_ID=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  provider2:
    build:
      context: ./producer
    environment:
      - PROVIDER_ID=2
    depends_on:
      rabbitmq:
        condition: service_healthy